import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../Components/Navbar";
import Footer from "../Components/Footer";
import Link from "next/link";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Client List | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Homepage</h1>
      <p className={styles.text}>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deserunt
        soluta laborum modi animi iure, laudantium assumenda enim obcaecati
        quisquam, architecto sint ratione at maxime illum, aspernatur fuga.
        Aperiam, dolorum pariatur.
      </p>
      <p className={styles.text}>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deserunt
        soluta laborum modi animi iure, laudantium assumenda enim obcaecati
        quisquam, architecto sint ratione at maxime illum, aspernatur fuga.
        Aperiam, dolorum pariatur.
      </p>
      <Link href="/clients">
        <a className={styles.btn}>See Clients</a>
      </Link>
    </div>
  );
}
